### ISSUE TITLE
After importing a database dump, apply custom settings

### ISSUE THREAD

**Issue by hiberus-magento** [hiberus-magento/hiberus-dockergento#139]
After importing an external database dump, some of the entries in `core_config_data` table could be invalid. For example:

- web/secure/offloader_header: Should be set to X-Forwarded-Proto
- web/cookie/cookie_domain
- web/unsecure/base_url
- web/secure/base_url
- catalog/search/elasticsearch7_server_hostname
- catalog/search/elasticsearch7_server_port
- catalog/search/elasticsearch7_server_username
- catalog/search/elasticsearch7_server_password
- admin/security/admin_account_sharing = 1
- admin/security/session_lifetime = 31536000
- admin/security/password_lifetime = NULL
- admin/security/password_is_forced = 0

Solution approach:
- During docker environment creation, create a config file "docker-options.yml" (or CSV if it's easier) with the following format:

```
options:
    web/secure/offloader_header: X-Forwarded-Proto
    web/cookie/cookie_domain: ...
    web/unsecure/base_url: ...
    web/secure/base_url: ...
    catalog/search/elasticsearch7_server_hostname: ...
    catalog/search/elasticsearch7_server_port: ...
    catalog/search/elasticsearch7_server_username: ...
    catalog/search/elasticsearch7_server_password: ...
    [...]
```

Create a new task launched after every database import for reading this file and applying each config option using the following command: `bin/magento setup:config:set XXX XXXX`

In each project, the teach leader could modify this file for including new entries manually.
